version: '3'

services:
  grav-webservice:
    build: .
    image: grav:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - grav_data:/var/www/html

volumes:
  grav_data:
    external: false
