name: Get latest grav release version
on:
  schedule:
    - cron:  '* 22 * * *'
  workflow_dispatch:
 
jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SCOPED_TOKEN }}
      - name: Fetch release version
        run: |
          echo ${{ secrets.REPO_SCOPED_TOKEN }} | gh auth login --scopes [repo,read:org] --with-token
          gh release list
          curl -sL https://api.github.com/repos/getgrav/grav/releases/latest | \
          jq -r ".tag_name" > release-versions/grav.txt
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$([ -z "$(git status --porcelain)" ] && echo "false" || echo "true")
      - name: Commit latest release version
        if: steps.git-check.outputs.modified == 'true'
        run: |          
          git config --global user.name '${{ secrets.REPO_USERNAME }}'
          git config --global user.email '${{ secrets.REPO_EMAIL }}'
          git add release-versions/grav.txt
          git pull --no-commit && git commit -m "New grav release version $(cat release-versions/grav.txt)"
          git push origin
          git tag -a grav-$(cat release-versions/grav.txt) -m "New grav release version $(cat release-versions/grav.txt)"
          git push origin --tags
          gh release create grav-$(cat release-versions/grav.txt)
